version: '3.7'
services:
  oracle:
    build: .
    environment:
      - ETH1_NODE=http://192.168.1.36:8545
      - ETH2_NODE=http://192.168.1.36:5052
      - REGISTRY_CONTRACT=0x5ec5DDf7A0cdD3235AD1bCC0ad04F059507EC5a3
      - ORACLE_CONTRACT=0x12aa6ec7d603dc79eD663792E40a520B54A7ae6A
      - MANAGER_PRIV_KEY=0xa8a54b2d8197bc0b19bb8a084031be71835580a01e70a45a13babd16c9bc1563
      - REGISTRY_ABI_FILE=assets/NodeOperatorsRegistry.json
      - ORACLE_ABI_FILE=assets/LidoOracle.json
      - REPORT_INTVL_SLOTS=7200
