version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true

volumes:
  ipfs_data:

services:

  lido-oracle-accounting-v6-1:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5681:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_1}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_1}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: accounting

  lido-oracle-ejector-v6-1:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5682:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_2}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: ejector

  lido-oracle-csm-v6-1:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5683:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_3}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_3}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "CSM_MODULE_ADDRESS=${CSM_MODULE_ADDRESS}"
      - "CSM_ORACLE_MAX_CONCURRENCY=1"
      - "PINATA_JWT=${PINATA_JWT}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: csm

  lido-oracle-accounting-v6:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5684:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_1}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_1}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: accounting

  lido-oracle-ejector-v6:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5685:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_2}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: ejector

  lido-oracle-csm-v6:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5686:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI_3}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_3}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "CSM_MODULE_ADDRESS=${CSM_MODULE_ADDRESS}"
      - "CSM_ORACLE_MAX_CONCURRENCY=1"
      - "PINATA_JWT=${PINATA_JWT}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
      - "KUBO_HOST=http://ipfs"
    command: csm

  ipfs:
    build: ./kubo
    container_name: lido-oracle-kubo
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    restart: unless-stopped
    volumes:
      - ipfs_data:/data/ipfs
    command:
      - daemon
      - --migrate=true
      - --agent-version-suffix=docker
    environment:
      CHAIN: artifact

