BLST_SUCCESS: int

class SecretKey:
    def keygen(self, ikm: bytes) -> None: ...

class P1_Affine:
    def __init__(self, data: bytes) -> None: ...
    # Uncompressed encoding, 96 bytes. Only used by tests, to build inputs the
    # deposit verifier must reject.
    def serialize(self) -> bytes: ...

class P1:
    def __init__(self, sk: SecretKey) -> None: ...
    def compress(self) -> bytes: ...

class P2_Affine:
    def __init__(self, data: bytes) -> None: ...
    # Uncompressed encoding, 192 bytes. See P1_Affine.serialize.
    def serialize(self) -> bytes: ...
    def core_verify(self, pk: P1_Affine, hash_or_encode: bool, msg: bytes, dst: bytes) -> int: ...

class P2:
    def __init__(self) -> None: ...
    def hash_to(self, msg: bytes, dst: bytes) -> P2: ...
    def sign_with(self, sk: SecretKey) -> P2: ...
    def compress(self) -> bytes: ...
