FAR_FUTURE_EPOCH = 2 ** 64 - 1
MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 256
EPOCHS_PER_SLASHINGS_VECTOR = 8192
PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX = 3
EFFECTIVE_BALANCE_INCREMENT = 2 ** 0 * 10 ** 9
MIN_DEPOSIT_AMOUNT = 32 * 10 ** 9
