FROM python:3.8-alpine
COPY requirements.txt /requirements.txt
RUN pip install -r requirements.txt
COPY check_bot.py /check_bot.py
COPY check_bot.py /check_bot.py
ENTRYPOINT ["python", "/check_bot.py"]
