name: CI Build prod image

on:
  workflow_call:
    inputs:
      tag:
        description: "tag to deploy from"
        default: ""
        required: false
        type: string

permissions:
  contents: read

jobs:
  # test:
  #   ...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Tag name
        id: tag_name
        run: |
          if [ '${{ inputs.tag }}' = '' ]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=$TAG" >> $GITHUB_OUTPUT
          fi
        env:
          TAG: ${{ inputs.tag }}

      - name: Build prod image
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TAG: "${{ steps.tag_name.outputs.TAG }}"
          TARGET_WORKFLOW: "build_mainnet_lido_oracle.yaml"
