name: Tests and checks

on: [push]

jobs:
  test:
    name: App tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Lint
      run: ./check_code.sh
      continue-on-error: true
    - name: Test with pytest and Lighthouse beacon
      run: ./run_tests.sh Lighthouse

    - name: Test with pytest and Prysm beacon
      run: ./run_tests.sh Prysm

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
